### ISSUE TITLE
Bard Death Bug

### ISSUE THREAD

**Issue by laiyna** [Nyyrazzilyss/NyyLIB#180]
When I die as a bard and I had a song running the interface could bug out (happens about 50% of the time), most commands no longer go to the mud, also no songs can be activated.
Only solution I have found is a restart of the session. In a zone that is not ideal.

**Comment by Nyyrazzilyss** [comment]
Had some difficulties attempting to duplicate. There was a bug with fugue entry not being properly recognized that might have been related to this. It was previously corrected, but hasn't been posted.

https://github.com/Nyyrazzilyss/NyyLIB/issues/176

It's an easy fix, and might be where this bug was happening. Had you made that change?

**Comment by laiyna** [comment]
found the typo, changed it, we gone test it soon enough :)
