### ISSUE TITLE
Displacement

### ISSUE THREAD

**Issue by Fisig** [Nyyrazzilyss/NyyLIB#220]
Displacement autocast doesnt seem to notice when it drops on others.
Also a status button similar to stn/blr/glb/vit would be awesome if it can fit.

**Comment by Fisig** [comment]
There is no room echo from the mud when it drops on someone else.

**Comment by Nyyrazzilyss** [comment]
Change the spellout trigger to the following, it will pick up more spellout messages. Since the mud doesn't provide a spellout message, there's no other way (other then spell timing out) that it will catch it had dropped other then if you status the character.

@set endspell dsp will change the final spell displayed from vit to dsp

([A-Za-z]+) group-says '.*(Displace|displace|DISPLACE).+'

**Comment by Nyyrazzilyss** [comment]
12/16/18 dev
