### ISSUE TITLE
Issue with aliases that send '.' speedwalks + commands

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#41]
Looks like something changed, maybe with new #fwalk code "-- fwalk buffers path, and sends in 5-10 room bursts" ?

I have a bunch of aliases that execute speedwalks using '.' nomenclature, followed by commands to do something, followed by more speedwalks then more commands, etc.  Always worked fine.

Now, I just tested this from the SM Inn as an example in a single alias:

expandAlias(".n12e2ne")
send("hello beldor")
send("hello ormast")

The 'hello' commands get executed in the middle of the speedwalk, then the speedwalk completes, which is bad for scripting stuff.  Not sure whats different now?

I also tried substituting mud:send(".n12e2ne") and #fwalk to the room # in place of the expandAlias line above, with the same result. 

I have upgraded, so this is all on the most current version.

**Comment by Nyyrazzilyss** [comment]
The command was changed, yes.

From the changelog:
-- fwalk buffers path, and sends in 5-10 room bursts

The entire speedwalk path is no longer sent all at once, it's sent in segments. This is so that the path can be aborted if something goes wrong (running in to a locked door, running out of moves, etc etc) without a long buffer of commands having been sent to the mud that are going to fail.

It does also mean that typing a command while a path is been walked through (example: ACC) won't be buffered until after the path completes / will be inserted into the path.

Sorry I hadn't thought about how that would impact aliases, but it will show up anytime you try walking a path > 10 rooms. Aliases will need to be changed as to how they recognize the path being completed - Simply having 'sent' the command isn't going to be enough going forwards.

**Comment by Hibbidy** [comment]
Can you add the old speedwalk back for speedwalks starting with lets say ',' (or some other character) and keep the buffering for those starting with '.' ?  (Will make it easier to find/replace and fix a ton of these that i have set up)

**Comment by Hibbidy** [comment]
Also possibly add a switch to #fwalk also to not buffer (for those who have scripts set up similarly with #fwalk - maybe something like: expandAlias("#fwalk 48603", nobuffer)

**Comment by Nyyrazzilyss** [comment]
What I can/ will do is change the buffer size to be a set'able variable, allowing you to for example increase it from 10 rooms to 100 rooms.

**Comment by Nyyrazzilyss** [comment]
011dev 09/30

set movebuffer 25 - paths less then 25 rooms will be sent in a single burst
